// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
   DB_URL: string;
   DB_TOKEN: string;
}

declare module "__STATIC_CONTENT_MANIFEST" {
   const value: string;
   export default value;
}
